name: Type Check

on: [push, pull_request]

jobs:
  build:
    name: "Type Check Code Base"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Install Dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-dev
      - name: "Set up Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: "Install Pyright"
        run: |
          npm install -g pyright
      - name: "Type Check with Pyright"
        run: |
          pyright flask_firebase_admin/
